FROM oven/bun:latest AS base

WORKDIR /app

FROM base AS deps
COPY package.json bun.lock* ./
RUN bun install --no-save --frozen-lockfile

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
WORKDIR /app
COPY . .
RUN bunx prisma generate

FROM base AS runner
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl 
WORKDIR /app
COPY --from=builder /app ./
USER 1001:1001

CMD bun dev