services:
  server:
    container_name: fieldlink-back
    hostname: fieldlink-server
    build: 
      context: .
      dockerfile: Dockerfile.bun
    environment:
      - PORT=${PORT}
      - REGION_MINIO=${REGION_MINIO}
      - URL_MINIO=${URL_MINIO}
      - URL_PUBLIC_MINIO=${URL_PUBLIC_MINIO}
      - ACCESS_KEY_MINIO=${ACCESS_KEY_MINIO}
      - SECRET_KEY_MINIO=${SECRET_KEY_MINIO}
      - URL_MONGO=${URL_MONGO}
      - GOOGLE_KEY=${GOOGLE_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - URL_FRONT=${URL_FRONT}
      - KEY_TOKEN=${KEY_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL} 
      - BETTER_AUTH_URI=${BETTER_AUTH_URI}
    ports:
      - "${PORT}:3333"
  # minio:
  #   image: minio/minio:latest
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     - MINIO_ROOT_USER=root
  #     - MINIO_ROOT_PASSWORD=changemeplease123
  #   volumes:
  #     - ./minio:/data
  #     - ./minio/config:/root/.minio
  #   command: server /data --console-address ":9001"
  # db:
  #   image: postgres:15.3-alpine
  #   container_name: fieldlink-db
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: 6t666GegibIkQU8eOAR00E9qudLG4y7p
  #     POSTGRES_DB: fieldlink-db
  #   restart: no
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
