services:

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: fieldlink
      MONGO_INITDB_ROOT_PASSWORD: CwFToy2aIDNP1oaV3Tug0rj1gFWYhnPh

# Use root/example as user/password credentials
